apiVersion: v1
kind: Service
metadata:
  name: boss-nlb
  namespace: prod
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-name: "boss-nlb"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb-ip"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-xxx, subnet-xxx
    service.beta.kubernetes.io/aws-load-balancer-private-ipv4-addresses: 10.200.x.x, 10.200.x.x
spec:
  type: LoadBalancer
  selector:
    app: boss
  ports:
  - name: http
    port: 80
    targetPort: 80
