apiVersion: v1
kind: Namespace
metadata:
  name: ops
  labels:
    pod-security.kubernetes.io/enforce: restricted

apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins2eks
  namespace: ops

---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: "jenkins2eks"
  name: jenkins2eks
  namespace: ops
type: kubernetes.io/service-account-token

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-r
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["create","delete","get","list","patch","update","watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get","list","watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "create", "list", "patch", "update", "watch"]
- apiGroups: ["policy"]
  resources: ["poddisruptionbudgets"]
  verbs: ["get", "create", "list", "patch", "update", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulset"]
  verbs: ["get", "create", "list", "patch", "update", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins-r
subjects:
- kind: ServiceAccount
  name: jenkins2eks
  namespace: ops
